# Generated by Django 4.2.7 on 2023-11-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                ("name", models.CharField(max_length=20)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.FloatField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
