# Generated by Django 4.2.7 on 2023-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="image",
            field=models.URLField(
                default="https://ik.imagekit.io/demo/tr:di-medium_cafe_B1iTdD0C.jpg/non_existent_image.jpg"
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="name",
            field=models.CharField(default="Item", max_length=20),
        ),
        migrations.AlterField(
            model_name="items",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
