# Generated by Django 4.2.7 on 2023-11-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_items_image_alter_items_name_alter_items_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="items",
            old_name="name",
            new_name="item_name",
        ),
    ]
